disabled_rules:
  - multiple_closures_with_trailing_closure
  - opening_brace
  - trailing_whitespace
  
opt_in_rules:
  - empty_count
  - redundant_optional_initialization

analyzer_rules:
  - explicit_self
  - unused_declaration

allow_zero_lintable_files: false

strict: false

force_cast: warning
force_try:
  severity: warning

line_length: 110

type_body_length:
  - 200
  - 500

file_length:
  warning: 600
  error: 1500

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode"
